config/routes.rb
Rails.application.routes.draw do

  # get 'welcome/show'
  # get 'welcome/:user_entry', to: 'welcome#show'
  get '/static_pages/home', to: 'static_pages#home'
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'
  post '/static_pages/home', to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users 
end

app/models/concerns/home_controller.rb
class HomeController < ApplicationController
  def home
    @random_number = rand(1000)
    puts "vous êtes #{@random}"
  end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
    has_many :join_table_gossip_tags
    has_many :tags, through: :join_table_gossip_tags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationContoller
  def home
    @random_number = rand(100)
    #puts "vous êtes #{@random}"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.first
     @user = User.new
    @user.first_name = params["first_name"]
    @user.save
    #puts "vous êtes #{@random}"
  end

  # def index
  #   user = User.new
  #   user.first_name = params["first_name"]
  #   user.save
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Gossip Project</title>
  <!-- <link rel="stylesheets"  href="style.css"> -->
  <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-kW2H6mf/72/MKlmwB//Zcwg0ckiegojPx/fio14/rpoYw2LMhULTn5YhS1QyrQfx" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", static_pages_home_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Team", static_pages_team_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", static_pages_contact_path %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <%= yield %>
</body>
</html>

app/views/static_pages/contact.html.erb
<!-- <h1>StaticPages#contact</h1> -->
<p>hey hey hey</p>

app/views/static_pages/home.html.erb
<p> Welcome <%= @user.first_name %> </p>
<form action '/static_pages/home' method="post">
	<input type="hidden" name="authenticity_token" value="<%=
	form_authenticity_token %>">
	<input type="text" name="first_name">
	<input type="submit" name="Evoyer">
</form>

app/views/static_pages/team.html.erb
<!-- <h1>StaticPages#team</h1> -->
<p>La team est composée de : Esteban Petaflop & Johnny Pepere</p>

app/views/welcome/show.html.erb
<h1>Bienvenue #params[:user_entry] !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>